module.exports = [
    {
        date: "April 15",
        name: "Income",
        amount: 1000,
        from: "Future Employer",
        category: "Pay Day",
    },
    {
        date: "April 19",
        name: "Taxes",
        amount: -300,
        from: "Government",
        category: "Taxes",
    },
    {
        date: "April 26",
        name: "Netflix",
        amount: -20,
        from: "Company",
        category: "Subscriptions",
    },
    {
        date: "July 18",
        name: "Savings",
        amount: -100,
        from: "Bank",
        category: "Rainy Day",
    },
    {
        date: "August 17",
        name: "Credit Card Payment",
        amount: -100,
        from: "Bank",
        category: "Minimum Payment",
    },
    {
        date: "September 20",
        name: "Monthly Birthday Money from Aunt Hilda",
        amount: 20,
        from: "Family",
        category: "Birthdays",
    },
    {
        date: "November 10",
        name: "Coffee",
        amount: -4,
        from: "Cafe",
        category: "Food",
    },
    {
        date: "November 28",
        name: "Internet",
        amount: -100,
        from: "Cablevision",
        category: "Utilities",
    },
    {
        date: "December 24",
        name: "Groceries",
        amount: -76,
        from: "Supermarket",
        category: "Essentials",
    },
    {
        date: "December 31",
        name: "Disney+",
        amount: -7,
        from: "Disney",
        category: "Subscriptions",
    },
];